filter:
  excluded_paths:
    - ".github/"
    - "tests/"
    - "vendor/"
    - "config/"

checks:
  php: true
    excluded_dependencies:
      - limedeck/phpunit-detailed-printer
      - orchestra/testbench
      - phpunit/phpunit
      - roave/security-advisories
      - phpstan/phpstan
      - phpstan/phpstan-strict-rules
      - thecodingmachine/phpstan-strict-rules
      - ergebnis/phpstan-rules
      - friendsofphp/php-cs-fixer

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true

build:
  nodes:
    tests:
      dependencies:
        before:
          - sudo apt-get update && sudo apt-get install -fyqq git ssh
  tests:
    override:
      - command: 'php ./vendor/bin/phpunit --coverage-clover=coverage-clover'
        coverage:
          file: 'coverage-clover'
          format: 'php-clover'
